"""
Django settings for NewsStudyRostelecom project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import environ
env = environ.Env()
environ.Env.read_env()
sc = env('SECRET_KEY')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = sc

# SECURITY WARNING: don't run with debug turned on in production!

# #Для проверки своей страницы 404, конфигурация такая:
# DEBUG = False
# ALLOWED_HOSTS = ["*"]
# # #В режиме отладки такая:
DEBUG = True
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'home',
    'news',
    'bootstrap5',
    'users',
    'debug_toolbar',
    'crispy_forms',
    'crispy_bootstrap5',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]
INTERNAL_IPS = ['127.0.0.1',]
ROOT_URLCONF = 'NewsStudyRostelecom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'all_apps/templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NewsStudyRostelecom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = { 'default':
              { 'ENGINE': 'django.db.backends.postgresql_psycopg2',
                'NAME': 'RealDjangoDb',
                'USER': 'postgres',
                'PASSWORD': '12345',
                'HOST': '127.0.0.1',
                'PORT': '5432'
                }
              }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'#'en-us'
LANGUAGES = [
    ('en',('English')),
    ('ru',('Russian')),
]

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)
MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'
MODELTRANSLATION_PREPOPULATE_LANGUAGE = 'ru' #для автзаполнения slug





TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
    "home/static/",
]
# Полный сброс миграции таблиц
# python manage.py migrate --fake-initial
#python manage.py flush - полный сброс базы включая суперпользователей
'''
Сброс миграции отдельной таблицы
python manage.py migrate --fake MyApp zero
python manage.py makemigrations
'''
import os
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATES_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

LOGIN_URL = 'login'


#Что нужно доделать:

#Скрипт для вывода автозаполнения поверх + кнопка с результатами (готово)
#для ремонта отображения поверх, добавьте стиль:
# .ui-front {
# 	z-index: 999999;
# }
#логика функций поиска прописана в приложении news/views.py (функция search и доработана функция index)



#Обвешать все функциями декоратором Login_required и check_group
#Пагинация списка новостей (Готово)
#Аутентификации при регистрации - (готово)
#Страница "мои закладки" (избранное)
#Страница "мои новости" с фильтрами по просмотрам-темам-тегам (Сделано с фильтром по категориям)

#Бонус - форма для входа не на отдельной странице, а в боковом меню !!!!!!!!!!!!!!!!!
#Бонус - сделать избранные теги
#Бонус 3 - комментарии к новостям
#Заявка - автовыход из аккаунта. Пример https://stackoverflow.com/questions/14830669/how-to-expire-django-session-in-5minutes
#Проверить title всех страниц


#https://github.com/PythonIgorTeacher/DjangoNewsRostelecom.git
#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