# Generated by Django 4.2.6 on 2023-12-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_author_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='status_en',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='status_ru',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_ru',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
